### ISSUE TITLE
Seesaw soil sensor getting spurious readings

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_seesaw#23]
see https://github.com/adafruit/Adafruit_Blinka/issues/84 !

**Comment by caternuson** [comment]
PR'd #24 

Things to note. All open for discussion.

* Went back to original read code timing since increasing it did not seem to fix problem
* Using magic numbers for reading threshold (4095) and max retries (3), wanted to keep modifications very local in code
* Raising an exception if retries exceeded

**Comment by caternuson** [comment]
I'll take PR merge-ment as acceptance. Closing for now.
